name: '[GCP] Backend Deployment'

on:
  push:
    branches: [develop, master, pipeline]
  pull_request:
    branches: [develop, master]
    types: [opened, synchronize]

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: natgas-server

jobs:
  deploy-gcr:
    name: Deploy to GCR
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build & Push
        run: |
          gcloud config set project $PROJECT_ID
          gcloud builds submit --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
          gcloud config set run/region $RUN_REGION
        working-directory: server

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated