name: '[GCP] Natgas Client Deployment'

on:
  push:
    branches: [develop, master, pipeline]
  pull_request:
    branches: [develop, master]
    types: [opened, synchronize]

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: natgas-client

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
        
      - name: Setup Node.js (NPM)
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build Development
        working-directory: client
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: client/build

  deploy-gcr:
    name: Deploy to GCR
    needs: build
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: .docker/build

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ inputs.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1


      - name: Build & Push
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
        working-directory: .docker

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated