name: NatGas Application Deployment

on:
  push:
    branches:
      - develop
      - pipeline

jobs:
  deploy_frontend:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        ref: develop
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install front dependencies
      working-directory: client
      run: npm ci
    - name: Install back dependencies
      working-directory: server
      run: npm ci
    - name: Test
      uses: cypress-io/github-action@v2.9.7
      with:
        command: 'cd client && npm run test'
        start: 'cd client && npm run start, cd server && npm run start'
        wait-on: 'http://localhost:3000, http://localhost:5959'