name: NatGas Application Deployment

on:
  push:
    branches:
      - develop
      - pipeline

jobs:
  deploy_frontend:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        ref: develop
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with:
        node-version: '14'
    - name: Install dependencies
      working-directory: client
      run: npm ci

