name: '[GCP] Application Deployment'

on:
  push:
    branches: [develop, pipeline, master]
  pull_request:
    branches: [develop, master]
    types: [opened, synchronize]

jobs:
  deploy_frontend:
    runs-on: ubuntu-18.04
    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install front dependencies
      working-directory: client
      run: npm ci
    - name: Install back dependencies
      working-directory: server
      run: npm ci
    - name: Test
      uses: cypress-io/github-action@v2.9.7
      with:
        command: 'cd client && npm run test'
        start: 'cd client && npm run start, cd server && npm run start'
        wait-on: 'http://localhost:3000, http://localhost:5959'